//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0.
namespace Aetheros.OneM2M.Binding
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Xml.Serialization;
	using Newtonsoft.Json;
	using Newtonsoft.Json.Linq;

	public partial class PrimitiveContent
	{
		[JsonProperty("acp")]
		[XmlElement("acp")]
		public AccessControlPolicy AccessControlPolicy { get; set; }

		[JsonProperty("ae")]
		[XmlElement("ae")]
		public AE AE { get; set; }

		[JsonProperty("cnt")]
		[XmlElement("cnt")]
		public Container Container { get; set; }

		[JsonProperty("cin")]
		[XmlElement("cin")]
		public ContentInstance ContentInstance { get; set; }

		[JsonProperty("cb")]
		[XmlElement("cb")]
		public CSEBase CSEBase { get; set; }

		[JsonProperty("dlv")]
		[XmlElement("dlv")]
		public Delivery Delivery { get; set; }

		[JsonProperty("evcg")]
		[XmlElement("evcg")]
		public EventConfig EventConfig { get; set; }

		[JsonProperty("exin")]
		[XmlElement("exin")]
		public ExecInstance ExecInstance { get; set; }

		[JsonProperty("grp")]
		[XmlElement("grp")]
		public Group Group { get; set; }

		[JsonProperty("lcp")]
		[XmlElement("lcp")]
		public LocationPolicy LocationPolicy { get; set; }

		[JsonProperty("mssp")]
		[XmlElement("mssp")]
		public M2MServiceSubscriptionProfile M2MServiceSubscriptionProfile { get; set; }

		[JsonProperty("mgc")]
		[XmlElement("mgc")]
		public MgmtCmd MgmtCmd { get; set; }

		//[JsonProperty("")]
		//[XmlElement("")]
		//public MgmtObj MgmtObj { get; set; }

		[JsonProperty("nod")]
		[XmlElement("nod")]
		public Node Node { get; set; }

		[JsonProperty("pch")]
		[XmlElement("pch")]
		public PollingChannel PollingChannel { get; set; }

		[JsonProperty("csr")]
		[XmlElement("csr")]
		public RemoteCSE RemoteCSE { get; set; }

		[JsonProperty("req")]
		[XmlElement("req")]
		public Request Request { get; set; }

		[JsonProperty("sch")]
		[XmlElement("sch")]
		public Schedule Schedule { get; set; }

		[JsonProperty("asar")]
		[XmlElement("asar")]
		public ServiceSubscribedAppRule ServiceSubscribedAppRule { get; set; }

		[JsonProperty("svsn")]
		[XmlElement("svsn")]
		public ServiceSubscribedNode ServiceSubscribedNode { get; set; }

		[JsonProperty("stcl")]
		[XmlElement("stcl")]
		public StatsCollect StatsCollect { get; set; }

		[JsonProperty("stcg")]
		[XmlElement("stcg")]
		public StatsConfig StatsConfig { get; set; }

		[JsonProperty("sub")]
		[XmlElement("sub")]
		public Subscription Subscription { get; set; }

		[JsonProperty("smd")]
		[XmlElement("smd")]
		public SemanticDescriptor SemanticDescriptor { get; set; }

		[JsonProperty("ntpr")]
		[XmlElement("ntpr")]
		public NotificationTargetMgmtPolicyRef NotificationTargetMgmtPolicyRef { get; set; }

		[JsonProperty("ntp")]
		[XmlElement("ntp")]
		public NotificationTargetPolicy NotificationTargetPolicy { get; set; }

		[JsonProperty("pdr")]
		[XmlElement("pdr")]
		public PolicyDeletionRules PolicyDeletionRules { get; set; }

		//[JsonProperty("")]
		//[XmlElement("")]
		//public FlexContainer FlexContainer { get; set; }

		[JsonProperty("ts")]
		[XmlElement("ts")]
		public TimeSeries TimeSeries { get; set; }

		[JsonProperty("tsi")]
		[XmlElement("tsi")]
		public TimeSeriesInstance TimeSeriesInstance { get; set; }

		[JsonProperty("rol")]
		[XmlElement("rol")]
		public Role Role { get; set; }

		[JsonProperty("tk")]
		[XmlElement("tk")]
		public Token Token { get; set; }

		[JsonProperty("trpt")]
		[XmlElement("trpt")]
		public TrafficPattern TrafficPattern { get; set; }

		[JsonProperty("dac")]
		[XmlElement("dac")]
		public DynamicAuthorizationConsultation DynamicAuthorizationConsultation { get; set; }

		[JsonProperty("acpA")]
		[XmlElement("acpA")]
		public AccessControlPolicyAnnc AccessControlPolicyAnnc { get; set; }

		[JsonProperty("aeA")]
		[XmlElement("aeA")]
		public AEAnnc AEAnnc { get; set; }

		[JsonProperty("cntA")]
		[XmlElement("cntA")]
		public ContainerAnnc ContainerAnnc { get; set; }

		[JsonProperty("cinA")]
		[XmlElement("cinA")]
		public ContentInstanceAnnc ContentInstanceAnnc { get; set; }

		[JsonProperty("grpA")]
		[XmlElement("grpA")]
		public GroupAnnc GroupAnnc { get; set; }

		[JsonProperty("lcpA")]
		[XmlElement("lcpA")]
		public LocationPolicyAnnc LocationPolicyAnnc { get; set; }

		//[JsonProperty("")]
		//[XmlElement("")]
		//public MgmtObjAnnc MgmtObjAnnc { get; set; }

		[JsonProperty("nodA")]
		[XmlElement("nodA")]
		public NodeAnnc NodeAnnc { get; set; }

		[JsonProperty("csrA")]
		[XmlElement("csrA")]
		public RemoteCSEAnnc RemoteCSEAnnc { get; set; }

		[JsonProperty("schA")]
		[XmlElement("schA")]
		public ScheduleAnnc ScheduleAnnc { get; set; }

		[JsonProperty("smdA")]
		[XmlElement("smdA")]
		public SemanticDescriptorAnnc SemanticDescriptorAnnc { get; set; }

		//[JsonProperty("")]
		//[XmlElement("")]
		//public FlexContainerAnnc FlexContainerAnnc { get; set; }

		[JsonProperty("tsa")]
		[XmlElement("tsa")]
		public TimeSeriesAnnc TimeSeriesAnnc { get; set; }

		[JsonProperty("tsia")]
		[XmlElement("tsia")]
		public TimeSeriesInstanceAnnc TimeSeriesInstanceAnnc { get; set; }

		[JsonProperty("trptA")]
		[XmlElement("trptA")]
		public TrafficPatternAnnc TrafficPatternAnnc { get; set; }
		//[JsonProperty("")]
		//[XmlElement("")]
		//public DynamicAuthorizationConsultationAnnc DynamicAuthorizationConsultationAnnc { get; set; }
	}

	public partial class ResponseContent
	{
		[JsonIgnore]
		[XmlIgnore]
		public ResponseStatusCode ResponseStatusCode { get; set; }
	}

	public class NotificationContent
	{
		[JsonProperty("sgn")]
		[XmlElement("sgn")]
		public Notification Notification { get; set; }
	}

	public partial class NotificationNotificationEvent
	{
		[JsonIgnore]
		[XmlIgnore]
		public RequestPrimitive PrimitiveRepresentation { get; set; }
	}





	public class SingleOrArrayConverter<T> : JsonConverter
	{
		public override bool CanConvert(Type objectType) => typeof(List<T>) == objectType;
		public override bool CanWrite => true;

		public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
		{
			var token = JToken.Load(reader);
			if (token.Type == JTokenType.Array)
				return token.ToObject<List<T>>();
			return new List<T> { token.ToObject<T>() };
		}

		public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
		{
			var list = (List<T>) value;
			if (list.Count == 1)
				value = list[0];
			serializer.Serialize(writer, value);
		}
	}

	public class JsonArrayItem<T> : JsonConverter
	{
		string _itemName;
		public JsonArrayItem(string itemName)
		{
			_itemName = itemName;
		}

		public override bool CanWrite => true;
		public override bool CanConvert(Type objectType) => true;

		public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
		{
			var token = JToken.Load(reader);
			if (token.Type != JTokenType.Object)
				return null;    // throw
			var obj = (JObject) token;
			if (obj.Count != 1)
				return null;    // throw
			var items = obj[_itemName];
			return items.Select(ch => ch.ToObject<T>()).ToList();
		}

		public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
		{
			var list = (List<T>) value;
			writer.WriteStartObject();
			writer.WritePropertyName(_itemName);
			serializer.Serialize(writer, value);
			writer.WriteEndObject();
		}
	}
}
